language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - sed -i 's/CLIENT_ID/'$clientID'/g' blog/.vuepress/config.js
  - sed -i 's/CLIENT_SECRET/'$clientSecret'/g' blog/.vuepress/config.js
  - yarn build
  - sed -i 's/href="\/rss.xml"/href="\/blog\/rss.xml"/g' blog/.vuepress/dist/index.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: blog/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master